### ISSUE TITLE
Responsivity could be helping more with container parent/child rearrangement (dynamic)

### ISSUE THREAD

**Issue by thadguidry** [sneikki/tidgrid#70]
![Screenshot 2023-12-08 183724](https://github.com/sneikki/tidgrid/assets/986438/d38cf3e5-20e4-4a50-9ffd-6a0d9db37e45)

Imagine that I want to design an interactive Records (tree/container) UI or additional library.
As a user, I want to interactively use my mouse to hover over any container object of my tree data representation and then be able to move a ghost image of it (or it's ghost border) and move it into another target parent container where the target parent container would have its border or fill area highlighted or color changed.

As is often the case with Record data (messy data)...Containers may or may not contain Record data that should be displayed (option: display subdata or not, i.e. **BOX A has values AND a container node BOX B** but in the image above BOX A option is not to display data, but only its child nodes and their data.  I.E. BOX A has setting to not display its own data, only child nodes and their data).

```json
{
    "BOX A": [
        {
            "somedata": "value1",
            "moredata": "value2",
            "BOX B": [
                {
                    "BOX C": [
                        "age": 18
                    ],
                    "BOX D": [
                        {
                            "value": "date of birth",
                            "value": "address"
                        }
                    ]
                }
            ]
        }
    ]
}
```

1. hover over and highlight BOX C (which optionally can highlight all other contained children (all leaves on its same branch, if the data representation was Records or JSON trees, for example)
2. Click and release with left mouse button on BOX C (which also moves BOX D) to initiate move control.
3. BOX C and BOX D are ghost outlined to represent they can now move with mouse control.
4. Move the children to one of the outer fill areas of BOX A.
5. BOX A is highlighted (target selected) as being the potential new parent of BOX C and BOX D
6. Click left mouse button on BOX A to finalize the move of BOX C and BOX D to new target parent BOX A

Part of the problem here is doing a lot of JavaScript coding heavy lifting, but you might have other additional ideas of how your library might be more enhanced to help make it easier to design and develop interactive UIs for general parent/child grid rearrangements with mouse or touch.

If this is outside the realm or a very long tail feature of **tidgrid** then I would also be interested and open to hear if you or others know of other libraries that already can handle most of this heavy lifting for its 2 needed primary parts.
1. Generating CSS Grid containers from JSON tree data (nodes and their data), then
2. Allowing interactivity for rearranging parent/child containers

UPDATE:  Perhaps one library that seems to address the needs above would be https://gridstackjs.com/demo/nested.html ?

**Comment by sneikki** [comment]
You need to dynamically adjust the styles associated to the elements using JS. This is about software logic, CSS only affects the styling. You may use any CSS library/framework or just pure CSS to achieve the styles addresses in the issue, but a proper implementation to handle the logic behind the interactivity is needed and is thus outside the scope of what Tidgrids aims to solve.

By investigating the demo site using DevTools you can relatively easily figure out how to implement all this. Probably there are libraries already delivering solution, but this is straightforward to solve without any of them, too.
